services:
  - type: web
    name: django-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn core.wsgi:application
    plan: free
    region: singapore
    rootDir: BackEnd
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
