import tshirt from "../assets/products/image 7.png";
import jeans from "../assets/products/image 8.png";
import shirt from "../assets/products/image 9.png";
import sleeve from "../assets/products/image 10.png";
import sleeve1 from "../assets/products/image 11.png";
import sleeve2 from "../assets/products/image 12.png";
import sleeve3 from "../assets/products/image 13.png";
import sleeve4 from "../assets/products/image 14.png";
const products = [
  {
    id: 1,
    name: "T-shirt with Tape Details",
    image: tshirt,
    price: "$120",
    rating: "4.5",
  },
  {
    id: 2,
    name: "Skinny Fit Jeans",
    image: jeans,
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    rating: "3.5",
  },
  {
    id: 3,
    name: "Checkered Shirt",
    image: shirt,
    price: "$180",
    rating: "4.5",
  },
  {
    id: 4,
    name: "Sleeve Striped T-shirt",
    image: sleeve,
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    rating: "4",
  },
  {
    id: 1,
    name: "T-shirt with Tape Details",
    image: sleeve1,
    price: "$120",
    rating: "4.5",
  },
  {
    id: 2,
    name: "Skinny Fit Jeans",
    image: sleeve2,
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    rating: "3.5",
  },
  {
    id: 3,
    name: "Checkered Shirt",
    image: sleeve3,
    price: "$180",
    rating: "4.5",
  },
  {
    id: 4,
    name: "Sleeve Striped T-shirt",
    image: sleeve4,
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    rating: "4",
  },
  {
    id: 1,
    name: "T-shirt with Tape Details",
    image: tshirt,
    price: "$120",
    rating: "4.5",
  },
  {
    id: 2,
    name: "Skinny Fit Jeans",
    image: jeans,
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    rating: "3.5",
  },
  {
    id: 3,
    name: "Checkered Shirt",
    image: shirt,
    price: "$180",
    rating: "4.5",
  },
  {
    id: 4,
    name: "Sleeve Striped T-shirt",
    image: sleeve,
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    rating: "4",
  },
  {
    id: 1,
    name: "T-shirt with Tape Details",
    image: sleeve1,
    price: "$120",
    rating: "4.5",
  },
  {
    id: 2,
    name: "Skinny Fit Jeans",
    image: sleeve2,
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    rating: "3.5",
  },
  {
    id: 3,
    name: "Checkered Shirt",
    image: sleeve3,
    price: "$180",
    rating: "4.5",
  },
  {
    id: 4,
    name: "Sleeve Striped T-shirt",
    image: sleeve4,
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    rating: "4",
  },
  {
    id: 1,
    name: "T-shirt with Tape Details",
    image: tshirt,
    price: "$120",
    rating: "4.5",
  },
  {
    id: 2,
    name: "Skinny Fit Jeans",
    image: jeans,
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    rating: "3.5",
  },
  {
    id: 3,
    name: "Checkered Shirt",
    image: shirt,
    price: "$180",
    rating: "4.5",
  },
  {
    id: 4,
    name: "Sleeve Striped T-shirt",
    image: sleeve,
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    rating: "4",
  },
  {
    id: 1,
    name: "T-shirt with Tape Details",
    image: sleeve1,
    price: "$120",
    rating: "4.5",
  },
  {
    id: 2,
    name: "Skinny Fit Jeans",
    image: sleeve2,
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    rating: "3.5",
  },
  {
    id: 3,
    name: "Checkered Shirt",
    image: sleeve3,
    price: "$180",
    rating: "4.5",
  },
  {
    id: 4,
    name: "Sleeve Striped T-shirt",
    image: sleeve4,
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    rating: "4",
  },
  {
    id: 1,
    name: "T-shirt with Tape Details",
    image: tshirt,
    price: "$120",
    rating: "4.5",
  },
  {
    id: 2,
    name: "Skinny Fit Jeans",
    image: jeans,
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    rating: "3.5",
  },
  {
    id: 3,
    name: "Checkered Shirt",
    image: shirt,
    price: "$180",
    rating: "4.5",
  },
  {
    id: 4,
    name: "Sleeve Striped T-shirt",
    image: sleeve,
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    rating: "4",
  },
  {
    id: 1,
    name: "T-shirt with Tape Details",
    image: sleeve1,
    price: "$120",
    rating: "4.5",
  },
  {
    id: 2,
    name: "Skinny Fit Jeans",
    image: sleeve2,
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    rating: "3.5",
  },
  {
    id: 3,
    name: "Checkered Shirt",
    image: sleeve3,
    price: "$180",
    rating: "4.5",
  },
  {
    id: 4,
    name: "Sleeve Striped T-shirt",
    image: sleeve4,
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    rating: "4",
  },
];
export default products;