const products = [
  {
    id: 1,
    name: "Gradient Graphic T-shirt",
    image: "/images/products/Gradient-Graphic-T-shirt.webp",
    price: 120,
    color: ["pink", "white", "black"],
    size: ["Small", "Medium", "Large", "X-Large"],
    rating: 4.5,
  },
  {
    id: 2,
    name: "Polo with Tipping Details",
    image: "/images/products/Polo-with-Tipping-Details.webp",
    price: 240,
    oldPrice: 260,
    discount: "20%",
    color: ["red", "yellow", "orange"],
    size: ["XX-Small", "X-Small", "Small", "Medium", "Large",],
    rating: 3.5,
  },
  {
    id: 3,
    name: "Black Striped T-shirt",
    image: "/images/products/Black-Striped-T-shirt.webp",
    price: 180,
    color: ["red", "yellow", "orange"],
    size: ["Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large", "4X-Large"],
    rating: 4.5,
  },
  {
    id: 4,
    name: "SKINNY FIT JEANS",
    image: "/images/products/SKINNY-FIT-JEANS.webp",
    price: 130,
    oldPrice: 160,
    discount: "30%",
    color: ["cyan", "blue", "purple"],
    size: [ "X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large", "4X-Large"],
    rating: 4,
  },
  {
    id: 5,
    name: "CHECKERED SHIRT",
    image: "/images/products/CHECKERED-SHIRT.webp",
    price: 120,
    color: ["cyan", "green", "purple"],
    size: ["XX-Small", "X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large"],
    rating: 4.5,
  },
  {
    id: 6,
    name: "SLEEVE STRIPED T-SHIRT",
    image: "/images/products/SLEEVE-STRIPED-T-SHIRT.webp",
    price: 240,
    oldPrice: 260,
    discount: "20%",
    color: ["black", "green", "purple"],
    size: ["XX-Small", "X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large", "4X-Large"],
    rating: 3.5,
  },
  {
    id: 7,
    name: "VERTICAL STRIPED SHIRT",
    image: "/images/products/VERTICAL-STRIPED-SHIRT.webp",
    price: 180,

    color: ["green", "red", "purple"],
    size: ["X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large", "4X-Large"],
    rating: 4.5,
  },
  {
    id: 8,
    name: "COURAGE GRAPHIC T-SHIRT",
    image: "/images/products/COURAGE-GRAPHIC-T-SHIRT.webp",
    price: 130,
    oldPrice: 160,
    discount: "30%",
    color: ["blue", "purple", "pink"],
    size: ["XX-Small", "X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large", "4X-Large"],
    rating: 4,
  },
  {
    id: 9,
    name: "LOOSE FIT BERMUDA SHORTS",
    image: "/images/products/LOOSE-FIT-BERMUDA-SHORTS.webp",
    price: 120,
    color: ["red", "purple", "pink"],
    size: ["Small", "Medium", "Large", "X-Large"],
    rating: 4.5,
  },
  {
    id: 10,
    name: "Polo with Contrast Trims",
    image: "/images/products/Polo-with-Contrast-Trims.webp",
    price: 240,
    oldPrice: 260,
    discount: "20%",

    color: ["blue", "purple", "cyan"],
    size: ["X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large"],
    rating: 3.5,
  },
  {
    id: 11,
    name: "One Life Graphic T-shirt",
    image: "/images/products/One-Life-Graphic-T-shirt.webp",
    price: "$180",
    color: ["blue", "red", "yellow"],
    size: ["X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large"],
    rating: 4.5,
  },
  {
    id: 12,
    name: "Sleeve Striped T-shirt",
    image: "/images/products/SLEEVE-STRIPED-T-SHIRT.webp",
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    color: ["orange", "red", "yellow"],
    size: ["Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large"],
    rating: 4,
  },
  {
    id: 13,
    name: "T-shirt with Tape Details",
    image: "/images/products/T-SHIRT-WITH-TAPE-DETAILS.webp",
    price: "$120",
    color: ["orange", "black", "yellow"],
    size: ["XX-Small", "X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large"],
    rating: 4.5,
  },
  {
    id: 14,
    name: "Skinny Fit Jeans",
    image: "/images/products/SKINNY-FIT-JEANS.webp",
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    colors: ["green", "white", "black"],
    size: ["Small", "Medium", "Large", "X-Large", "XX-Large"],
    rating: 3.5,
  },
  {
    id: 15,
    name: "Checkered Shirt",
    image: "/images/products/CHECKERED-SHIRT.webp",
    price: "$180",
    colors: ["orange", "purple", "white",],
    size: ["X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large"],
    rating: 4.5,
  },
  {
    id: 16,
    name: "Sleeve Striped T-shirt",
    image: "/images/products/SLEEVE-STRIPED-T-SHIRT.webp",
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    colors: ["orange", "white", "black"],
    size: ["Small", "Medium", "Large", "X-Large"],
    rating: 4,
  },
  {
    id: 17,
    name: "T-shirt with Tape Details",
    image: "/images/products/T-SHIRT-WITH-TAPE-DETAILS.webp",
    price: "$120",
    colors: ["blue", "white", "black"],
    size: ["X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large"],
    rating: 4.5,
  },
  {
    id: 18,
    name: "Skinny Fit Jeans",
    image: "/images/products/SKINNY-FIT-JEANS.webp",
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    colors: ["orange", "pink", "white",],
    size: ["Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large", "4X-Large"],
    rating: 3.5,
  },
  {
    id: 19,
    name: "Checkered Shirt",
    image: "/images/products/CHECKERED-SHIRT.webp",
    price: "$180",
    colors: ["green", "red", "blue"],
    size: ["XX-Small", "X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large"],
    rating: 4.5,
  },
  {
    id: 20,
    name: "Sleeve Striped T-shirt",
    image: "/images/products/SLEEVE-STRIPED-T-SHIRT.webp",
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    colors: ["red", "yellow", "orange"],
    size: [ "X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large", "4X-Large"],
    rating: 4,
  },
  {
    id: 21,
    name: "T-shirt with Tape Details",
    image: "/images/products/T-SHIRT-WITH-TAPE-DETAILS.webp",
    price: "$120",
    colors: ["yellow", "orange", "black"],
    size: ["XX-Small", "X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large"],
    rating: 4.5,
  },
  {
    id: 22,
    name: "Skinny Fit Jeans",
    image: "/images/products/SKINNY-FIT-JEANS.webp",
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    colors: ["cyan", "purple", "white"],
    size: ["X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large"],
    rating: 3.5,
  },
  {
    id: 23,
    name: "Checkered Shirt",
    image: "/images/products/CHECKERED-SHIRT.webp",
    price: "$180",
    colors: ["yellow", "orange", "purple"],
    size: ["X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large"],
    rating: 4.5,
  },
  {
    id: 24,
    name: "Sleeve Striped T-shirt",
    image: "/images/products/SLEEVE-STRIPED-T-SHIRT.webp",
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    colors: ["yellow", "cyan", "purple"],
    size: ["Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large"],
    rating: 4,
  },
  {
    id: 25,
    name: "T-shirt with Tape Details",
    image: "/images/products/T-SHIRT-WITH-TAPE-DETAILS.webp",
    price: "$120",
    colors: ["red", "white", "black"],
    size: ["Small", "Medium", "Large", "X-Large", "XX-Large"],
    rating: 4.5,
  },
  {
    id: 26,
    name: "Skinny Fit Jeans",
    image: "/images/products/SKINNY-FIT-JEANS.webp",
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    colors: ["yellow", "white", "black"],
    size: ["X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large"],
    rating: 3.5,
  },
  {
    id: 27,
    name: "Checkered Shirt",
    image: "/images/products/CHECKERED-SHIRT.webp",
    price: "$180",
    colors: ["cyan", "white", "black"],
    size: ["X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large"],
    rating: 4.5,
  },
  {
    id: 28,
    name: "Sleeve Striped T-shirt",
    image: "/images/products/SLEEVE-STRIPED-T-SHIRT.webp",
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    colors: ["pink", "white", "black"],
    size: ["Small", "Medium", "Large", "X-Large", "XX-Large"],
    rating: 4,
  },
  {
    id: 29,
    name: "T-shirt with Tape Details",
    image: "/images/products/T-SHIRT-WITH-TAPE-DETAILS.webp",
    price: "$120",
    colors: ["yellow", "white", "black"],
    size: ["X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large"],
    rating: 4.5,
  },
  {
    id: 30,
    name: "Skinny Fit Jeans",
    image: "/images/products/SKINNY-FIT-JEANS.webp",
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    colors: ["orange", "white", "black"],
    size: ["Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large", "4X-Large"],
    rating: 3.5,
  },
  {
    id: 31,
    name: "Checkered Shirt",
    image: "/images/products/CHECKERED-SHIRT.webp",
    price: "$180",
    colors: ["purple", "white", "black"],
    size: ["X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large", "3X-Large"],
    rating: 4.5,
  },
  {
    id: 32,
    name: "Sleeve Striped T-shirt",
    image: "/images/products/SLEEVE-STRIPED-T-SHIRT.webp",
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    colors: ["green", "blue", "white"],
    size: ["XX-Small", "X-Small", "Small", "Medium", "Large", "X-Large", "XX-Large"],
    rating: 4,
  },
];
export default products;