const products = [
  {
    id: 1,
    name: "T-shirt with Tape Details",
    image: "/images/products/T-SHIRT-WITH-TAPE-DETAILS.svg",
    price: "$120",
    rating: "4.5",
  },
  {
    id: 2,
    name: "Skinny Fit Jeans",
    image: "/images/products/SKINNY-FIT-JEANS.svg",
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    rating: "3.5",
  },
  {
    id: 3,
    name: "Checkered Shirt",
    image: "/images/products/CHECKERED-SHIRT.svg",
    price: "$180",
    rating: "4.5",
  },
  {
    id: 4,
    name: "Sleeve Striped T-shirt",
    image: "/images/products/Sleeve-Striped-T-shirt.svg",
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    rating: "4",
  },
  {
    id: 5,
    name: "T-shirt with Tape Details",
    image: "/images/products/T-shirt-with-Tape-Details.svg",
    price: "$120",
    rating: "4.5",
  },
  {
    id: 6,
    name: "Skinny Fit Jeans",
    image: "/images/products/Skinny-Fit-Jeans.svg",
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    rating: "3.5",
  },
  {
    id: 7,
    name: "Checkered Shirt",
    image: "/images/products/Checkered-Shirt.svg",
    price: "$180",
    rating: "4.5",
  },
  {
    id: 8,
    name: "Sleeve Striped T-shirt",
    image: "/images/products/Sleeve-Striped-T-shirt.svg",
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    rating: "4",
  },
  {
    id: 9,
    name: "T-shirt with Tape Details",
    image: "/images/products/T-shirt-with-Tape-Details.svg",
    price: "$120",
    rating: "4.5",
  },
  {
    id: 10,
    name: "Skinny Fit Jeans",
    image: "/images/products/Skinny-Fit-Jeans.svg",
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    rating: "3.5",
  },
  {
    id: 11,
    name: "Checkered Shirt",
    image: "/images/products/Checkered-Shirt.svg",
    price: "$180",
    rating: "4.5",
  },
  {
    id: 12,
    name: "Sleeve Striped T-shirt",
    image: "/images/products/Sleeve-Striped-T-shirt.svg",
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    rating: "4",
  },
  {
    id: 13,
    name: "T-shirt with Tape Details",
    image: "/images/products/T-shirt-with-Tape-Details.svg",
    price: "$120",
    rating: "4.5",
  },
  {
    id: 14,
    name: "Skinny Fit Jeans",
    image: "/images/products/Skinny-Fit-Jeans.svg",
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    rating: "3.5",
  },
  {
    id: 15,
    name: "Checkered Shirt",
    image: "/images/products/CHECKERED-SHIRT.svg",
    price: "$180",
    rating: "4.5",
  },
  {
    id: 16,
    name: "Sleeve Striped T-shirt",
    image: "/images/products/SLEEVE-STRIPED-T-SHIRT.svg",
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    rating: "4",
  },
  {
    id: 17,
    name: "T-shirt with Tape Details",
    image: "/images/products/T-SHIRT-WITH-TAPE-DETAILS.svg",
    price: "$120",
    rating: "4.5",
  },
  {
    id: 18,
    name: "Skinny Fit Jeans",
    image: "/images/products/SKINNY-FIT-JEANS.svg",
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    rating: "3.5",
  },
  {
    id: 19,
    name: "Checkered Shirt",
    image: "/images/products/CHECKERED-SHIRT.svg",
    price: "$180",
    rating: "4.5",
  },
  {
    id: 20,
    name: "Sleeve Striped T-shirt",
    image: "/images/products/SLEEVE-STRIPED-T-SHIRT.svg",
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    rating: "4",
  },
  {
    id: 21,
    name: "T-shirt with Tape Details",
    image: "/images/products/T-SHIRT-WITH-TAPE-DETAILS.svg",
    price: "$120",
    rating: "4.5",
  },
  {
    id: 22,
    name: "Skinny Fit Jeans",
    image: "/images/products/SKINNY-FIT-JEANS.svg",
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    rating: "3.5",
  },
  {
    id: 23,
    name: "Checkered Shirt",
    image: "/images/products/CHECKERED-SHIRT.svg",
    price: "$180",
    rating: "4.5",
  },
  {
    id: 24,
    name: "Sleeve Striped T-shirt",
    image: "/images/products/SLEEVE-STRIPED-T-SHIRT.svg",
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    rating: "4",
  },
  {
    id: 25,
    name: "T-shirt with Tape Details",
    image: "/images/products/T-SHIRT-WITH-TAPE-DETAILS.svg",
    price: "$120",
    rating: "4.5",
  },
  {
    id: 26,
    name: "Skinny Fit Jeans",
    image: "/images/products/SKINNY-FIT-JEANS.svg",
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    rating: "3.5",
  },
  {
    id: 27,
    name: "Checkered Shirt",
    image: "/images/products/CHECKERED-SHIRT.svg",
    price: "$180",
    rating: "4.5",
  },
  {
    id: 28,
    name: "Sleeve Striped T-shirt",
    image: "/images/products/SLEEVE-STRIPED-T-SHIRT.svg",
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    rating: "4",
  },
  {
    id: 29,
    name: "T-shirt with Tape Details",
    image: "/images/products/T-SHIRT-WITH-TAPE-DETAILS.svg",
    price: "$120",
    rating: "4.5",
  },
  {
    id: 30,
    name: "Skinny Fit Jeans",
    image: "/images/products/SKINNY-FIT-JEANS.svg",
    price: "$240",
    oldPrice: "$260",
    discount: "20%",
    rating: "3.5",
  },
  {
    id: 31,
    name: "Checkered Shirt",
    image: "/images/products/CHECKERED-SHIRT.svg",
    price: "$180",
    rating: "4.5",
  },
  {
    id: 32,
    name: "Sleeve Striped T-shirt",
    image: "/images/products/SLEEVE-STRIPED-T-SHIRT.svg",
    price: "$130",
    oldPrice: "$160",
    discount: "30%",
    rating: "4",
  },
];
export default products;